[pytest]
addopts = -s -v
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*
markers =
    regression: Маркировка для регрессионых тестов
    positive_advertisements_v1: Маркировка для позитивных тестов, связанных с объявлениями v1
    positive_advertisements_v2: Маркировка для позитивных тестов, связанных с объявлениями v2
    negative_advertisements_v1: Маркировка для негативных тестов, связанных с объявлениями v1
    negative_advertisements_v2: Маркировка для негативных тестов, связанных с объявлениями v2
    statistics_v1: Маркировка для тестов, связанных со статистикой v1
    statistics_v2: Маркировка для тестов, связанных со статистикой v2
